'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { DsButton as DsButtonElement, defineCustomElement as defineDsButton } from "@ds/web-components/dist/components/ds-button.js";
import { DsInput as DsInputElement, defineCustomElement as defineDsInput } from "@ds/web-components/dist/components/ds-input.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type DsButtonEvents = NonNullable<unknown>;

export const DsButton: StencilReactComponent<DsButtonElement, DsButtonEvents> = /*@__PURE__*/ createComponent<DsButtonElement, DsButtonEvents>({
    tagName: 'ds-button',
    elementClass: DsButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DsButtonEvents,
    defineCustomElement: defineDsButton
});

export type DsInputEvents = NonNullable<unknown>;

export const DsInput: StencilReactComponent<DsInputElement, DsInputEvents> = /*@__PURE__*/ createComponent<DsInputElement, DsInputEvents>({
    tagName: 'ds-input',
    elementClass: DsInputElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DsInputEvents,
    defineCustomElement: defineDsInput
});
