/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * Our custom button component
     */
    interface DsButton {
        /**
          * If the button is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * The type of the button
          * @default "button"
         */
        "type": 'button' | 'submit' | 'reset';
    }
    /**
     * Our custom input component
     */
    interface DsInput {
        /**
          * The label of the input
          * @required
         */
        "label": string;
        /**
          * The placeholder of the input
         */
        "placeholder": string;
        /**
          * If the input is required
         */
        "required": boolean;
        /**
          * The type of the input
          * @default "text"
         */
        "type": 'text' | 'email' | 'password' | 'number' | 'tel' | 'url';
    }
}
declare global {
    /**
     * Our custom button component
     */
    interface HTMLDsButtonElement extends Components.DsButton, HTMLStencilElement {
    }
    var HTMLDsButtonElement: {
        prototype: HTMLDsButtonElement;
        new (): HTMLDsButtonElement;
    };
    /**
     * Our custom input component
     */
    interface HTMLDsInputElement extends Components.DsInput, HTMLStencilElement {
    }
    var HTMLDsInputElement: {
        prototype: HTMLDsInputElement;
        new (): HTMLDsInputElement;
    };
    interface HTMLElementTagNameMap {
        "ds-button": HTMLDsButtonElement;
        "ds-input": HTMLDsInputElement;
    }
}
declare namespace LocalJSX {
    /**
     * Our custom button component
     */
    interface DsButton {
        /**
          * If the button is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * The type of the button
          * @default "button"
         */
        "type"?: 'button' | 'submit' | 'reset';
    }
    /**
     * Our custom input component
     */
    interface DsInput {
        /**
          * The label of the input
          * @required
         */
        "label"?: string;
        /**
          * The placeholder of the input
         */
        "placeholder"?: string;
        /**
          * If the input is required
         */
        "required"?: boolean;
        /**
          * The type of the input
          * @default "text"
         */
        "type"?: 'text' | 'email' | 'password' | 'number' | 'tel' | 'url';
    }
    interface IntrinsicElements {
        "ds-button": DsButton;
        "ds-input": DsInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Our custom button component
             */
            "ds-button": LocalJSX.DsButton & JSXBase.HTMLAttributes<HTMLDsButtonElement>;
            /**
             * Our custom input component
             */
            "ds-input": LocalJSX.DsInput & JSXBase.HTMLAttributes<HTMLDsInputElement>;
        }
    }
}
